platform :ios, '10.0'
use_frameworks!

target 'Balizinha_Example' do
  pod 'Balizinha', :path => '../'
  pod 'RenderPay', :git => 'git@bitbucket.org:renderapps/renderpay.git', :tag=>'0.2.0'
  pod 'RenderCloud', :git => 'git@bitbucket.org:renderapps/RenderCloud.git', :tag=>'1.3.0'
  pod 'Stripe', '14.0.0'
  pod 'RACameraHelper', :git => 'https://github.com/bobbyren/RACameraHelper', :tag => '0.1.5'
  
  # heatmaps
  # https://stackoverflow.com/questions/42611599/cocoapods-target-has-transitive-dependencies-that-include-static-binaries
  pod 'GoogleMaps'

  target 'Balizinha_Tests' do
    inherit! :search_paths

  end
end
