platform :ios, '10.0'
use_frameworks!

target 'Balizinha_Example' do
  pod 'Balizinha', :path => '../'

  ## local development
  #pod 'RenderCloud', :path => '../../rendercloud'
  #pod 'RenderPay', :path => '../../renderpay'

  ## pull from git for releases
  pod 'RenderPay', :git => 'git@bitbucket.org:renderapps/renderpay.git', :tag=>'1.0.0'
  pod 'RenderCloud', :git => 'git@bitbucket.org:renderapps/RenderCloud.git', :tag=>'2.0.0'
  pod 'RACameraHelper', :git => 'https://github.com/bobbyren/RACameraHelper', :tag => '0.1.5'

  ## third party platforms
  pod 'GoogleMaps' # https://stackoverflow.com/questions/42611599/cocoapods-target-has-transitive-dependencies-that-include-static-binaries

  target 'Balizinha_Tests' do
    inherit! :search_paths

  end
end
