platform :ios, '10.0'
use_frameworks!

target 'Balizinha_Example' do
  pod 'Balizinha', :path => '../'
  pod 'RenderPay', :git => 'git@bitbucket.org:renderapps/renderpay.git', :tag=>'0.1.3'
  pod 'RenderCloud', :git => 'git@bitbucket.org:renderapps/RenderCloud.git', :tag=>'1.2.0'
  pod 'Stripe', '14.0.0'

  target 'Balizinha_Tests' do
    inherit! :search_paths

  end
end
